Class DnaTest.DataDictionary [ Abstract ]
{

ClassMethod SetChromosomeNames()
{
	kill ^chr
	set ^chr(1) = "1"
	set ^chr(2) = "2"
	set ^chr(3) = "3"
	set ^chr(4) = "4"
	set ^chr(5) = "5"
	set ^chr(6) = "6"
	set ^chr(7) = "7"
	set ^chr(8) = "8"
	set ^chr(9) = "9"
	set ^chr(10) = "10"
	set ^chr(11) = "11"
	set ^chr(12) = "12"
	set ^chr(13) = "13"
	set ^chr(14) = "14"
	set ^chr(15) = "15"
	set ^chr(16) = "16"
	set ^chr(17) = "17"
	set ^chr(18) = "18"
	set ^chr(19) = "19"
	set ^chr(20) = "20"
	set ^chr(21) = "21"
	set ^chr(22) = "22"
	set ^chr(23) = "X"
	set ^chr(24) = "Y"
	set ^chr = 24
}

}
